"""add collector_health table

Revision ID: 0cfc343ee649
Revises: f6fb267a569e
Create Date: 2026-03-13 10:01:34.951072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cfc343ee649'
down_revision: Union[str, Sequence[str], None] = 'f6fb267a569e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector_health',
    sa.Column('collector_name', sa.String(length=100), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=False),
    sa.Column('last_success', sa.DateTime(), nullable=True),
    sa.Column('records_collected', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('collector_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collector_health')
    # ### end Alembic commands ###
