"""add vendor_mapping table

Revision ID: f6fb267a569e
Revises: fe30a3dade5f
Create Date: 2026-03-10 20:34:20.044526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6fb267a569e'
down_revision: Union[str, Sequence[str], None] = 'fe30a3dade5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_mapping',
    sa.Column('vendor', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('vendor_url', sa.Text(), nullable=False),
    sa.Column('portal_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('vendor', 'state', 'county')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_mapping')
    # ### end Alembic commands ###
