"""create initial tables

Revision ID: fe30a3dade5f
Revises: 
Create Date: 2026-03-09 22:45:01.772025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe30a3dade5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auctions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('sale_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('registration_deadline', sa.Date(), nullable=True),
    sa.Column('deposit_deadline', sa.Date(), nullable=True),
    sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_bid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('property_count', sa.Integer(), nullable=True),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state', 'county', 'start_date', 'sale_type', name='uq_auction_dedup')
    )
    op.create_index(op.f('ix_auctions_county'), 'auctions', ['county'], unique=False)
    op.create_index(op.f('ix_auctions_start_date'), 'auctions', ['start_date'], unique=False)
    op.create_index(op.f('ix_auctions_state'), 'auctions', ['state'], unique=False)
    op.create_table('county_info',
    sa.Column('fips_code', sa.String(length=5), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('county_name', sa.String(length=100), nullable=False),
    sa.Column('treasurer_url', sa.Text(), nullable=True),
    sa.Column('tax_sale_page_url', sa.Text(), nullable=True),
    sa.Column('known_auction_vendor', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('fips_code')
    )
    op.create_index(op.f('ix_county_info_state'), 'county_info', ['state'], unique=False)
    op.create_table('state_rules',
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('sale_type', sa.String(length=10), nullable=False),
    sa.Column('statutory_timing_description', sa.Text(), nullable=True),
    sa.Column('typical_months', sa.JSON(), nullable=True),
    sa.Column('notice_requirement_weeks', sa.Integer(), nullable=True),
    sa.Column('redemption_period_months', sa.Integer(), nullable=True),
    sa.Column('public_notice_url', sa.Text(), nullable=True),
    sa.Column('state_agency_url', sa.Text(), nullable=True),
    sa.Column('governing_statute', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('state')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('state_rules')
    op.drop_index(op.f('ix_county_info_state'), table_name='county_info')
    op.drop_table('county_info')
    op.drop_index(op.f('ix_auctions_state'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_start_date'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_county'), table_name='auctions')
    op.drop_table('auctions')
    # ### end Alembic commands ###
